### ISSUE TITLE
cannot read pictures with "tif" format

### ISSUE THREAD

**Issue by zzy-ucas** [HuMingqi/AlexNet_tf#2]
Hello, there! New problems comes!

`img= tf.image.decode_jpeg(img_s,3)` and
`img= tf.image.decode_image(img_s,3)`
can only read pictures with "jpg", "png" and "gif". But I want to use pictures with "tif".
when I use `img= tf.image.decode_image(img_s,3)`, it occurred  errors.

Thanks!

**Comment by HuMingqi** [comment]
You means TIFF?
See there https://www.tensorflow.org/api_guides/python/image
So up to now there are no op decode_tif().
You may need to convert fromat to standard.

**Comment by zzy-ucas** [comment]
I have tried "PIL" and "cv2" to convert this "TIFF" to "JPEG". 

> from cv2 import imread
from cv2 import imwrite
img = imread('123.tif')
imwrite('123.jpg', img)

But there stills are errors when I running this code.

> InvalidArgumentError (see above for traceback): assertion failed: [Unable to decode bytes as JPEG, PNG, or GIF]
	 [[Node: decode_image/cond_jpeg/cond_png/Assert/Assert = Assert[T=[DT_STRING], summarize=3, _device="/job:localhost/replica:0/task:0/cpu:0"](decode_image/cond_jpeg/cond_png/is_gif, decode_image/cond_jpeg/cond_png/Assert/Assert/data_0)]]

God.... I have no idea...

**Comment by HuMingqi** [comment]
Use jpeginfo to check integrity of images : https://github.com/tjko/jpeginfo

**Comment by zzy-ucas** [comment]
I have solve the problem. What I should do is to convert the 'TIFF' to 'JPEG' not 'JPG'.
And do not put anything but pictures only in folders.
Thanks! I have a lot to learn...
